# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    env:
      DAY_OF_WEEK: Mon
      token_demo: "99999token"
      demo: "99999token"
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }} 
        cache: 'npm'
      env: 
        CODECOV_TOKENA: ${{ secrets.CODECOV_TOKEN }} 
      run: echo "$CODECOV_TOKENA"   


        #- run: npm ci
        # - run: npm run build --if-present
    - run: npm install codecov --global   
    - run: npm install  nyc@15.1.0 --global
    - run: npm install  mocha@9.1.3 --global
    - run: npm install 
    - run: npm test
    - run: npm run report-coverage
    - run: echo  "$CODECOV_TOKEN"
    - run: echo "$node-version"
    - run: echo "token demo params print:"
    - run: echo "$token_demo"
    - run: echo "$demo"
    - run: codecov --token  "$CODECOV_TOKEN"
